name: CI

on:
  push:
    branches: [master]
    paths:
      - "**.swift"
      - "**.podspec"
      - ".github/workflows/*"
  pull_request:
    branches: [master]
    paths:
      - "**.swift"
      - "**.podspec"
      - ".github/workflows/*"

jobs:
  build-mac:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build --build-tests
      - name: Run tests
        run: swift test --skip-build
      - name: Pod lint
        run: pod lib lint --quick
      - name: Verify Carthage
        run: carthage build --no-skip-current --verbose --use-xcframeworks --platform macOS

  build-ios:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          swift build -Xswiftc "-sdk" \
           -Xswiftc `xcrun --sdk iphonesimulator --show-sdk-path` \
           -Xswiftc "-target" \
           -Xswiftc "x86_64-apple-ios`xcrun --show-sdk-version --sdk iphonesimulator`-simulator"
