name: CI

on:
  push:
    branches: [master]
    paths:
      - "**.swift"
      - "**.podspec"
      - ".github/workflows/*"
  pull_request:
    branches: [master]
    paths:
      - "**.swift"
      - "**.podspec"
      - ".github/workflows/*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-mac:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build --build-tests
      - name: Run tests
        run: swift test --skip-build
      - name: Pod lint
        run: pod lib lint
      - name: Verify Carthage
        run: carthage build --no-skip-current --verbose --use-xcframeworks --platform macOS

  build-ios:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          set -o pipefail && xcodebuild \
           -scheme CombineCoreBluetooth \
           -workspace ./CombineCoreBluetooth.xcworkspace/ \
           -destination "platform=iOS Simulator,OS=16.2,name=iPhone 14" \
           -sdk iphonesimulator \
           -enableCodeCoverage YES \
           -disableAutomaticPackageResolution \
           test | xcpretty -c

  build-tvos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          set -o pipefail && xcodebuild \
           -scheme CombineCoreBluetooth \
           -workspace ./CombineCoreBluetooth.xcworkspace/ \
           -destination "platform=tvOS Simulator,OS=16.2,name=Apple TV" \
           -sdk appletvsimulator \
           -enableCodeCoverage YES \
           -disableAutomaticPackageResolution \
           test | xcpretty -c

  build-watchos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          set -o pipefail && xcodebuild \
           -scheme CombineCoreBluetooth \
           -workspace ./CombineCoreBluetooth.xcworkspace/ \
           -destination "platform=watchOS Simulator,OS=9.1,name=Apple Watch Ultra (49mm)" \
           -sdk watchsimulator \
           -enableCodeCoverage YES \
           -disableAutomaticPackageResolution \
           test | xcpretty -c
