name: CI

on:
  push:
    branches: [master]
    paths:
      - "**.swift"
      - "**.podspec"
      - ".github/workflows/*"
  pull_request:
    branches: [master]
    paths:
      - "**.swift"
      - "**.podspec"
      - ".github/workflows/*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
env:
  DEVELOPER_DIR: "/Applications/Xcode_15.2.app/Contents/Developer"

jobs:
  build-mac:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Update Tools
        run: gem update cocoapods
      - name: Print Versions
        run: |
          xcodebuild -version
          swift --version
          pod --version
      - name: Build
        run: swift build --build-tests
      - name: Run tests
        run: swift test --skip-build
      - name: Pod lint
        run: pod lib lint
      - name: Verify Carthage
        run: carthage build --no-skip-current --verbose --use-xcframeworks --platform macOS

  build-ios:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          set -o pipefail && xcodebuild \
           -scheme CombineCoreBluetooth \
           -workspace ./CombineCoreBluetooth.xcworkspace/ \
           -destination "platform=iOS Simulator,OS=latest,name=iPhone 15" \
           -sdk iphonesimulator \
           -enableCodeCoverage YES \
           -disableAutomaticPackageResolution \
           test | xcpretty -c

  build-tvos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          set -o pipefail && xcodebuild \
           -scheme CombineCoreBluetooth \
           -workspace ./CombineCoreBluetooth.xcworkspace/ \
           -destination "platform=tvOS Simulator,OS=latest,name=Apple TV" \
           -sdk appletvsimulator \
           -enableCodeCoverage YES \
           -disableAutomaticPackageResolution \
           test | xcpretty -c

  build-watchos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          set -o pipefail && xcodebuild \
           -scheme CombineCoreBluetooth \
           -workspace ./CombineCoreBluetooth.xcworkspace/ \
           -destination "platform=watchOS Simulator,OS=latest,name=Apple Watch Ultra (49mm)" \
           -sdk watchsimulator \
           -enableCodeCoverage YES \
           -disableAutomaticPackageResolution \
           test | xcpretty -c
  
  build-visionos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          set -o pipefail && xcodebuild \
           -scheme CombineCoreBluetooth \
           -workspace ./CombineCoreBluetooth.xcworkspace/ \
           -destination "platform=visionOS Simulator,OS=latest,name=Apple Vision Pro" \
           -sdk xrsimulator \
           -enableCodeCoverage YES \
           -disableAutomaticPackageResolution \
           test | xcpretty -c
